INSERT INTO DRONE_MODEL(ID,MAX_WEIGHT,NAME)
VALUES (1001,100,'Lightweight');

INSERT INTO DRONE_MODEL(ID,MAX_WEIGHT,NAME)
VALUES (1002,250,'Middleweight');

INSERT INTO DRONE_MODEL(ID,MAX_WEIGHT,NAME)
VALUES (1003,350,'Cruiserweight');

INSERT INTO DRONE_MODEL(ID,MAX_WEIGHT,NAME)
VALUES (1004,500,'Heavyweight');